### ISSUE TITLE
awk command in slide2mp4.sh does not work with gawk-5.1.0

### ISSUE THREAD

**Issue by nak3** [h-kojima/slide2mp4#1]
### Description

Running the sample does not work on Fedora 33 as:

```sh
$ ../slide2mp4.sh test-slides.pdf test-slides.txt test-lexicon.pls test-output.mp4
Format checking of input files is completed.
  ...
list.txt: No such file or directory
```
The root cause is that the `awk` in slide2mp4.sh:

https://github.com/h-kojima/slide2mp4/blob/e654143cd1aeea80150f16b4f2461dc300f63d38/slide2mp4.sh#L90

It does not work with gawk-5.1.0 which is installed by Fedora 23 RPM package, so script cannot complete.
It needed `awk '/<\?xml/,/<\/speak>/'` instead of `awk '/\<\?xml/,/\<\/speak\>/'` on my Fedora machine.

### Step to reproduce

- The following command does not work:

```sh
$ cat test-slides.txt |awk '/\<\?xml/,/\<\/speak\>/'
(not output)
```

- While, this `awk` command works.

```sh
$ cat test-slides.txt |awk '/<\?xml/,/<\/speak>/'
<?xml version="1.0" encoding="UTF-8"?>
<speak version="1.1">

<prosody rate="110%">
これはタイトルスライドであり、
これから、サンプルスライドをご紹介します。
OpenShiftとVirtualizationの読み上げテストもします。
</prosody>
 ... snp ..
```

My `awk` version is below.

```sh
$ rpm -qf `which awk`
gawk-5.1.0-2.fc33.x86_64
```

### Additional info (workaround on Fedora 33)

So `gawk-5.1.0` needed the following patch but I guess it will not work on Mac's awk?

```diff
diff --git a/slide2mp4.sh b/slide2mp4.sh
index 8a9c5a5..ea0a4ee 100755
--- a/slide2mp4.sh
+++ b/slide2mp4.sh
@@ -87,7 +87,8 @@ echo "Format checking of input files is completed."
 mkdir -p json mp3 mp4 png srt xml
 
 
-cat $TXT_FILE |awk '/\<\?xml/,/\<\/speak\>/' > tmp.txt
+cat $TXT_FILE |awk '/<\?xml/,/<\/speak>/' > tmp.txt
+
 cat << EOF   > txt2xml.py
 #!/usr/bin/python3
 # Usage: python3 txt2xml.py xml_txt
```

**Comment by h-kojima** [comment]
I've confirmed that I can reproduce this issue by using gawk on CentOS Stream release 8.
The `gawk` version is below.
```
$ cat /etc/redhat-release 
CentOS Stream release 8
$ rpm -qf `which awk`
gawk-4.2.1-2.el8.x86_64
```

I've applied the following patch to slide2mp4.sh.
https://github.com/h-kojima/slide2mp4/commit/a66ea15363d123307a1d898c5527735d16dcabdd

And, I've confirmed that it still works on macos Big Sur after applying this patch.
The `awk` version on macos is below.
```
$ awk --version
awk version 20200816
```

Please try to see if slide2mp4.sh works on Fedora.

**Comment by nak3** [comment]
Thank you! It worked :+1:
