### ISSUE TITLE
RFE: disable subtitle option

### ISSUE THREAD

**Issue by kmoriwak** [h-kojima/slide2mp4#2]
Disable subtitle option like '--no-subs' which disables following match my use case.
 - aws polly's json output (reduces cost & time)
 - change ffmpeg options

**Comment by h-kojima** [comment]
I've implemented disabling subtitles option, "-ns" or "--no-subtitles".
For example, `slide2mp4.sh -ns test.pdf test.txt test.pls test.mp4`.
https://github.com/h-kojima/slide2mp4/commit/673015b254423fc33d30f493a3021302a515e211

Please try to see if slidesmp4.sh works.

**Comment by kmoriwak** [comment]
Thank you!
