### ISSUE TITLE
Bug: Support filename which contains space characters

### ISSUE THREAD

**Issue by kmoriwak** [h-kojima/slide2mp4#3]
Reproducer:

$ slide2mp4.sh ./Value\ of\ subscription\ -\ RHEL.pdf ssml.txt lexicon.pls output.mp4
/home/kankun/bin/slide2mp4.sh: line 54: [: too many arguments
/home/kankun/bin/slide2mp4.sh: line 56: [: too many arguments
/home/kankun/bin/slide2mp4.sh: line 69: check_./Value.txt: No such file or directory

Because of my local patches, line numbers may be different.

**Comment by h-kojima** [comment]
I've applied the following patch to slide2mp4.sh.
https://github.com/h-kojima/slide2mp4/commit/9afcf3f07b01706b2184662afd4128dd12c21c03

Please try to see if slide2mp4.sh works.

**Comment by kmoriwak** [comment]
Thank you!
